language: node_js
cache: yarn

node_js: "10"

script: skip
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN

  local-dir: dist
  keep-history: false
  skip-cleanup: true
  on:
    branch: master
